name: example
description: A new Flutter application.

publish_to: 'none'

version: 1.1.1+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  di_module:
    path: ../
  provider: ^6.0.3
  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.2.0


flutter:

  uses-material-design: true


