name: example
description: A new Flutter application.

publish_to: 'none'

version: 1.1.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  di_module:
    path: ../
  provider: ^6.0.2
  cupertino_icons: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.1.0


flutter:

  uses-material-design: true


