name: di_module
description: A DI Flutter package
version: 1.1.2

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.2.0


flutter:
