name: di_module
description: A DI Flutter package
version: 1.1.0

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.1.0


flutter:
